---
- name: Install and Start the service 
  hosts: all
  vars:
    apps: [vim,httpd,telnet,apache]

  tasks:
  - name: Installing tools
    apt:
      name: "{{ item }}"
      state: present
    with_items: "{{ apps }}"

  - name: Starting the tools
    service:
      name: "{{ item }}"
      state: started
      enabled: true
    with_items: "{{ apps }}"
    
  